import { RecoilRoot } from 'recoil'
import '../styles/globals.css'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
function MyApp({ Component, pageProps }) {
  return (
    <RecoilRoot>
      <Head>
        <title>LeetClone</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon1.png' />
        <meta
          name='description'
          content='Web application that contains leetcode problems and video solutions'
        />
      </Head>
      <ToastContainer></ToastContainer>
      {/* <Head>
        <title>leet code clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Component {...pageProps} />
    </RecoilRoot>
  )
}

export default MyApp
